[workspace]
members  = ["api/lib", "api/shuttle", "shared"]
resolver = "2"

[workspace.dependencies]
# internal
# api-lib = { version = "0.1.0", path = "./api/lib" }
# shared = { version = "0.1.0", path = "./shared" }

