[package]
edition = "2021"
name    = "moviedevexperience"
version = "0.1.0"

[dependencies]
axum = "0.6.18"
shuttle-axum = "0.20.0"
shuttle-runtime = "0.20.0"
shuttle-shared-db = { version = "0.20.0", features = ["postgres"] }
sqlx = { version = "0.6.3", default-features = false, features = [
  "runtime-actix-native-tls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "json",
] }
tokio = "1.28.2"
