[package]
edition = "2021"
name    = "api-shuttle"
version = "0.1.0"

[dependencies]
actix-web         = "4.3.1"
shuttle-actix-web = "0.20.0"
shuttle-runtime   = "0.20.0"
tokio             = "1.26.0"
