[package]
edition = "2021"
name    = "shared"
version = "0.1.0"

[dependencies]
# serde
serde = { workspace = true }

# Sqlx, only when the backend add this as dependency is compiled
sqlx = { workspace = true, optional = true }

# utils
chrono = { workspace = true }
uuid   = { workspace = true }
